# This is a basic workflow to help you get started with Actions

name: ch generator

# Controls when the action will run. 
on:
  schedule:
    - cron: '0 0/1 * * *'
    
  pull_request:
    branches:
      - main
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      #- name: Run a one-line script
      #  run: echo testing!

      # Runs a set of commands using the runners shell 
      - name: config
        run: |
          git config --global user.email "gohhh40163@gmail.com"
          git config --global user.name "GOH3124"
      

      - name: Main
        run: |
          pwd
          chmod +x ch1.sh
          ./sh/ch1.sh

      - name: Main
        run: |
          pwd
          chmod +x ch2.sh
          ./ch2.sh

      - name: Main
        run: |
          pwd
          chmod +x ch3.sh
          ./ch3.sh
     
      - name: Main
        run: |
          pwd
          chmod +x ch4.sh
          ./ch4.sh

      - name: Main
        run: |
          pwd
          chmod +x ch5.sh
          ./ch5.sh

      - name: Main
        run: |
          pwd
          chmod +x ch6.sh
          ./ch6.sh

      - name: Main
        run: |
          pwd
          chmod +x ch7.sh
          ./ch7.sh

      - name: Main
        run: |
          pwd
          chmod +x ch8.sh
          ./ch8.sh

      - name: Main
        run: |
          pwd
          chmod +x ch9.sh
          ./ch9.sh
        
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git commit -m "link is updated"
          git push
